Algoritmo "Condicional"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/03/2024
Var
n1, n2: inteiro


Inicio
escreva ("Digite dois números inteiros:")
Leia (n1)
Leia (n2)

Se n1>n2 entao
Escreval ("O número: ", n1, " é maior")
senao
Escreval ("O número: ", n2, " é maior")
fimse


Fimalgoritmo