Algoritmo "CondicionalSimples"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/03/2024
Var
a, x: inteiro


Inicio
Escreva ("Digite um número inteiro: ")
Leia (a)
x<-a%2
Se x=0 entao
Escreval ("O Número: ", a, " é par")
Senao
Escreval ("O número: ", a, " é impar")
fimse

Fimalgoritmo