Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/03/2024
Var
n1 : inteiro
Inicio
Escreval("Digite um numero inteiro: ")
Leia(n1)
Se (n1 mod 2 = 0) Então
Escreval("O número",n1," é par")
Senao
Escreval("O número",n1," é ímpar")
Fimse
Fimalgoritmo