Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/03/2024
Var
n1, n2, n3: inteiro


Inicio
Escreva ("Informe o primeiro número:")
Leia (n1)
Escreva ("Informe o segundo número:")
Leia (n2)
n3 <- n1+n2
Escreva ("O resultado é:", n3)


Fimalgoritmo