Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/04/2024
Var
valorDigitado, soma: real


Inicio
soma <- 0
Repita
Escreva ("Digite um valor para a soma: ")
Leia (valorDigitado)
soma <- soma + valorDigitado
Escreval ("Total: ", soma)
Ate valorDigitado = 0


Fimalgoritmo