Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2024
Var
nota1, nota2: real
media: real


Inicio
Escreva ("Informe a primeira nota:")
Leia (nota1)
Escreva ("Informe a segunda nota:")
Leia (nota2)
media <- (nota1+nota2)/2
Escreval ("Sua média é:", media)


Fimalgoritmo