Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2024
Var
contador: inteiro
Inicio
contador <- 0
Enquanto (contador <= 10) faca
Escreval (contador)
contador <- contador + 1
Fimenquanto
Escreval ("Terminei de contar!")
Fimalgoritmo